name: deploy-pelican

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies and theme
      run: |
          echo "Install dependencies"
          pip install -r requirements.txt
          echo "Clone repo with pelican theme"
          git clone https://github.com/ingwinlu/pelican-twitchy
          echo "Install pelican theme"
          pelican-themes --install pelican-twitchy
    - name: Compile with pelican and publish
      run: |
          pelican content
      env:
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: blog-output/
        force_orphan: true
    