name: deploy-pelican

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies and theme
      run: |
          echo "Install dependencies"
          pip install -r requirements.txt
          echo "Clone repo with pelican theme"
          git clone https://github.com/ingwinlu/pelican-twitchy
          echo "Install pelican theme"
          pelican-themes --install pelican-twitchy
    - name: Compile with pelican and publish
      uses: vdmitriyev/pelican-to-github-pages@v1.4.1
      env:
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    